
env:
  browser: true
  es2021: true
extends: [airbnb-base, prettier]
overrides: []
parser: @babel/eslint-parser
parserOptions:
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: module
babelOptions:
  plugins: [@babel/plugin-syntax-import-assertions]
rules: {}
