env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
plugins:
  - import
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: warn
  no-empty: warn
  prefer-const: warn
